### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by mab85** [hamaadshah/gan_public#1]
@hamaadshah How can we compute the time of extract features per image?

**Comment by hamaadshah** [comment]
Hi there: Apologies for the late response however can you further elaborate on your question? Are you asking about a time dimension per image or the time to extract the features per image? Happy to help however not sure about the question. Best wishes, Hamaad.

**Comment by mab85** [comment]
@hamaadshah I ask about time to extract the features per images

**Comment by hamaadshah** [comment]
Hi: Good question however I haven't done time profiling for this - busy with other projects. Perhaps it might be an idea to run different GAN architectures and data sets to get a good estimate(s) for this. Best wishes, Hamaad.
